In [3]:
import numpy as np
import pandas as pd
array1 =np.array([1,2,4,5])
array2 =np.array([6,7,8,9])
result1 = np.multiply(array1,array2)
print(result1)

result2 = np.divide(array1,array2)
print(result2)

result3 = np.power(array1,array2)
print(result3)

[ 6 14 32 45]
[0.16666667 0.28571429 0.5        0.55555556]
[      1     128   65536 1953125]
